export type College = {
  id: string;
  name: string;
  location: string;
  fees: number;
  rating: number;
  description: string;
  placements: string;
  courses: string[];
  established: number;
  type: string;
};

export const colleges: College[] = [
  {
    id: "iit-delhi",
    name: "IIT Delhi",
    location: "Delhi",
    fees: 200000,
    rating: 4.9,
    description: "Indian Institute of Technology Delhi is one of the top engineering institutions in India, known for cutting-edge research and excellent placements.",
    placements: "45 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1961,
    type: "Government",
  },
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    location: "Mumbai",
    fees: 200000,
    rating: 4.9,
    description: "IIT Bombay is a premier engineering institution located in Mumbai, consistently ranked among the top universities in Asia.",
    placements: "50 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1958,
    type: "Government",
  },
  {
    id: "dtu",
    name: "DTU",
    location: "Delhi",
    fees: 200000,
    rating: 4.5,
    description: "Delhi Technological University (formerly DCE) is one of India's leading state engineering universities with strong industry connections.",
    placements: "22 LPA",
    courses: ["B.Tech", "M.Tech", "MBA"],
    established: 1941,
    type: "Government",
  },
  {
    id: "nsut",
    name: "NSUT",
    location: "Delhi",
    fees: 220000,
    rating: 4.4,
    description: "Netaji Subhas University of Technology is a renowned engineering university in Delhi known for its strong CS and IT programs.",
    placements: "21 LPA",
    courses: ["B.Tech", "M.Tech"],
    established: 1983,
    type: "Government",
  },
  {
    id: "iiit-delhi",
    name: "IIIT Delhi",
    location: "Delhi",
    fees: 350000,
    rating: 4.6,
    description: "Indraprastha Institute of Information Technology Delhi focuses on research-driven CS and ECE education with excellent faculty.",
    placements: "28 LPA",
    courses: ["B.Tech", "M.Tech", "PhD"],
    established: 2008,
    type: "Deemed",
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani",
    location: "Pilani, Rajasthan",
    fees: 500000,
    rating: 4.7,
    description: "BITS Pilani is a top private engineering university famous for its practice school program and strong alumni network in Silicon Valley.",
    placements: "35 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1964,
    type: "Deemed",
  },
  {
    id: "vit-vellore",
    name: "VIT Vellore",
    location: "Vellore, Tamil Nadu",
    fees: 400000,
    rating: 4.3,
    description: "Vellore Institute of Technology is one of India's largest private engineering universities with a strong focus on industry partnerships.",
    placements: "18 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1984,
    type: "Deemed",
  },
  {
    id: "srm",
    name: "SRM Institute",
    location: "Chennai, Tamil Nadu",
    fees: 350000,
    rating: 4.1,
    description: "SRM Institute of Science and Technology is a top private university with campuses across India offering diverse engineering programs.",
    placements: "15 LPA",
    courses: ["B.Tech", "M.Tech", "MBA"],
    established: 1985,
    type: "Deemed",
  },
  {
    id: "mit-manipal",
    name: "MIT Manipal",
    location: "Manipal, Karnataka",
    fees: 450000,
    rating: 4.4,
    description: "Manipal Institute of Technology is a prestigious private engineering college known for its international collaborations and vibrant campus life.",
    placements: "20 LPA",
    courses: ["B.Tech", "M.Tech"],
    established: 1957,
    type: "Deemed",
  },
  {
    id: "nit-trichy",
    name: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    fees: 150000,
    rating: 4.6,
    description: "National Institute of Technology Tiruchirappalli is consistently ranked as the best NIT in India with outstanding academic rigor.",
    placements: "30 LPA",
    courses: ["B.Tech", "M.Tech", "PhD"],
    established: 1964,
    type: "Government",
  },
  {
    id: "nit-warangal",
    name: "NIT Warangal",
    location: "Warangal, Telangana",
    fees: 150000,
    rating: 4.5,
    description: "NIT Warangal is one of the oldest and most prestigious NITs, known for excellent technical education and strong alumni network.",
    placements: "28 LPA",
    courses: ["B.Tech", "M.Tech", "PhD"],
    established: 1959,
    type: "Government",
  },
  {
    id: "iit-madras",
    name: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    fees: 200000,
    rating: 4.9,
    description: "IIT Madras is India's top-ranked engineering institution, home to numerous startups and a world-class research ecosystem.",
    placements: "48 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1959,
    type: "Government",
  },
  {
    id: "iit-kanpur",
    name: "IIT Kanpur",
    location: "Kanpur, Uttar Pradesh",
    fees: 200000,
    rating: 4.8,
    description: "IIT Kanpur is known for pioneering computer science education in India and producing top scientists and entrepreneurs globally.",
    placements: "44 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1959,
    type: "Government",
  },
  {
    id: "iit-kharagpur",
    name: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    fees: 200000,
    rating: 4.8,
    description: "The oldest IIT in India, IIT Kharagpur offers the widest range of programs and has produced many industry leaders and Nobel laureates.",
    placements: "42 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "Law", "PhD"],
    established: 1951,
    type: "Government",
  },
  {
    id: "jadavpur",
    name: "Jadavpur University",
    location: "Kolkata, West Bengal",
    fees: 50000,
    rating: 4.5,
    description: "Jadavpur University is one of the best state universities in India, highly regarded for engineering and science programs at very low cost.",
    placements: "25 LPA",
    courses: ["B.Tech", "M.Tech", "PhD"],
    established: 1955,
    type: "Government",
  },
  {
    id: "coep",
    name: "COEP Technological University",
    location: "Pune, Maharashtra",
    fees: 120000,
    rating: 4.3,
    description: "College of Engineering Pune is one of India's oldest engineering colleges, known for strong practical training and alumni in top tech companies.",
    placements: "18 LPA",
    courses: ["B.Tech", "M.Tech"],
    established: 1854,
    type: "Government",
  },
  {
    id: "thapar",
    name: "Thapar University",
    location: "Patiala, Punjab",
    fees: 380000,
    rating: 4.2,
    description: "Thapar Institute of Engineering and Technology is a top private technical university known for strong industry connections and research output.",
    placements: "16 LPA",
    courses: ["B.Tech", "M.Tech", "MBA"],
    established: 1956,
    type: "Deemed",
  },
  {
    id: "lnmiit",
    name: "LNMIIT Jaipur",
    location: "Jaipur, Rajasthan",
    fees: 280000,
    rating: 4.0,
    description: "LNM Institute of Information Technology is a premier private IT university in Rajasthan with a focus on technology and entrepreneurship.",
    placements: "14 LPA",
    courses: ["B.Tech", "M.Tech"],
    established: 2003,
    type: "Deemed",
  },
  {
    id: "pec",
    name: "PEC Chandigarh",
    location: "Chandigarh, Punjab",
    fees: 100000,
    rating: 4.1,
    description: "Punjab Engineering College is a prestigious government university in the Union Territory of Chandigarh with a strong engineering tradition.",
    placements: "15 LPA",
    courses: ["B.Tech", "M.Tech"],
    established: 1921,
    type: "Deemed",
  },
  {
    id: "rvce",
    name: "RVCE Bangalore",
    location: "Bangalore, Karnataka",
    fees: 220000,
    rating: 4.3,
    description: "R.V. College of Engineering is one of Bangalore's top private engineering colleges with excellent industry ties in India's tech capital.",
    placements: "17 LPA",
    courses: ["B.Tech", "M.Tech"],
    established: 1963,
    type: "Private",
  },
  {
    id: "pesit",
    name: "PES University",
    location: "Bangalore, Karnataka",
    fees: 300000,
    rating: 4.2,
    description: "PES University is a top-ranked private university in Bangalore known for innovation, strong CS program, and active startup culture.",
    placements: "16 LPA",
    courses: ["B.Tech", "M.Tech", "MBA"],
    established: 1972,
    type: "Deemed",
  },
  {
    id: "iit-roorkee",
    name: "IIT Roorkee",
    location: "Roorkee, Uttarakhand",
    fees: 200000,
    rating: 4.7,
    description: "IIT Roorkee is the oldest technical institution in Asia, renowned for civil engineering, architecture, and emerging technologies.",
    placements: "40 LPA",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    established: 1847,
    type: "Government",
  },
  {
    id: "nit-surathkal",
    name: "NIT Surathkal",
    location: "Surathkal, Karnataka",
    fees: 150000,
    rating: 4.4,
    description: "NIT Karnataka (Surathkal) is a top NIT on India's west coast known for strong engineering programs and coastal campus life.",
    placements: "26 LPA",
    courses: ["B.Tech", "M.Tech", "PhD"],
    established: 1960,
    type: "Government",
  },
  {
    id: "christ-university",
    name: "Christ University",
    location: "Bangalore, Karnataka",
    fees: 180000,
    rating: 4.0,
    description: "Christ University is a premier private institution offering diverse programs across engineering, arts, science, and management.",
    placements: "10 LPA",
    courses: ["B.Tech", "BCA", "MBA", "BBA"],
    established: 1969,
    type: "Deemed",
  },
  {
    id: "amity",
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    fees: 400000,
    rating: 3.9,
    description: "Amity University is one of India's largest private universities with campuses across India and abroad, offering diverse professional programs.",
    placements: "12 LPA",
    courses: ["B.Tech", "MBA", "BCA", "Law", "PhD"],
    established: 2005,
    type: "Private",
  },
];
